### ISSUE TITLE
Add a new class in a trained model

### ISSUE THREAD

**Issue by minitho** [pythonlessons/TensorFlow-2.x-YOLOv3#33]
Hi! My question here is if i can add a new class in a trained model and dont need to retrain all the model again with the new class and the old classes.

**Comment by pythonlessons** [comment]
No, you can't. It's impossible that the model will detect a new class without seeing and learning it. It's the same that I will ask you what is my weight, it's impossible to tell it because you didn't even saw me...
Best what you can do is add one more class and use transfer learning

**Comment by minitho** [comment]
Yeah, but with trafer leaning you lose accurancy when you add a few new classes.

**Comment by pythonlessons** [comment]
> Yeah, but with transfer learning you lose accurancy when you add a few new classes or not?

If you add these classes to COCO dataset, then yes, because I don't think that you have that computing resources. If for example, you use a model with 10 classes, and you add 2 more classes, everything depends on the dataset. If it's large enough and you train it for enough time you don't lose accuracy. But best to do testing for this.
