### ISSUE TITLE
Request a tutorial for int8 inference

### ISSUE THREAD

**Issue by Mercurise** [pythonlessons/TensorFlow-2.x-YOLOv3#68]
Great tutorial, **I have the questions on int8 model inference using TFLITE. Is it possible to introduce a bit about how to inference the int8 models?** I saw you've planned future works around tflite, but would be appreciate if you could give some insights. Thanks in advance. 

Here is some of my contexts for this question: 

As the int8 models (such as v3 tiny) produces predictions in int8 format, it is required to converted it back to fp32 for handling the predictions. I tried several approaches but found the **box scores all zeros** in v3 tiny after reversing to fp32. However, my inference steps work fine for fp32 tflite models, in which there are no int8 prediction converting procedures.

**Comment by pythonlessons** [comment]
Hi,
On what device you use TFLITE? 
Actually, I am not sure about doing tflite tutorial in near future, I don't have ideas for such tutorial right now. 

Actually, you don't need to do anything after conversion it is FP32, FP16 or INT8
But, maybe because I am doing this not with tflite, I am not sure.
Also, I noticed that there is some kind of bug, as you said, sometimes when I do the conversion to INT8. When I do detection there is no results, then I simply do the conversion again and it starts to work.
