### ISSUE TITLE
problem with detection_demo video 

### ISSUE THREAD

**Issue by MichaelDee98** [pythonlessons/TensorFlow-2.x-YOLOv3#93]
I am trying to run detection_demo.py and I get this error

> tensorflow.python.framework.errors_impl.FailedPreconditionError:  Error while reading resource variable batch_normalization_4/moving_variance_54800 from Container: localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/batch_normalization_4/moving_variance_54800/N10tensorflow3VarE does not exist.
> 	 [[{{node StatefulPartitionedCall/functional_1/batch_normalization_4/FusedBatchNormV3/ReadVariableOp_1}}]] [Op:__inference_signature_wrapper_5006]
> 
> Function call stack:
> signature_wrapper

Any idea how to fix this ?

**Comment by pythonlessons** [comment]
Does image detection work? what TensorFlow version do you use?

**Comment by MichaelDee98** [comment]
> Does image detection work? what TensorFlow version do you use?

Yes the image detection works and I am using tensorflow==2.3.1

**Comment by pythonlessons** [comment]
So this problem comes not from yolo algorithm, because video detection uses the same function as image detection. Make sure everything is fine with the video, try to read image frames from the video and visualize it on your screen, check frames shape and so on, but I am sure it's not a problem with detection functions.
